#STAGE 1: Build the application
FROM node:20 AS build

#Set working directory
WORKDIR /app

#Install dependencies
COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build

#STAGE 2: Run the application
FROM node:20-alpine

WORKDIR /app

# Copy only the built files and dependencies
COPY --from=build /app/build ./build
COPY package.json package-lock.json ./

#Do not also install development dependencies
RUN npm ci --only=production

#Port
EXPOSE 1234

# Start the server
CMD ["node", "build/app.js"]
