name: Frontend CI

on:
  push:
    branches:
      - main
      - production
  pull_request:
    branches:
      - main
      - production

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{runner.os}}-frontend-${{hashFiles('frontend/package-lock.json')}}
        restore-keys: |
          ${{runner.os}}-frontend-

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Create .env
      # Set BACKEND_API_URL in .env
      run: |
        echo "BACKEND_API_URL=${{vars.BACKEND_API_URL}}" >> frontend/.env
        cat frontend/.env

    - name: Build application
      run: |
        cd frontend
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/

  test-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: frontend/node_modules
        key: ${{runner.os}}-frontend-${{hashFiles('frontend/package-lock.json')}}
        restore-keys: |
          ${{runner.os}}-frontend-

    - name: Install dependencies
      run: |
        cd frontend
        npm install

    - name: Run tests with coverage
      run: |
        cd frontend
        npm run test:ci

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: frontend-coverage
        path: frontend/coverage/

  dockerize-and-push-dev:
    needs: test-frontend
    runs-on: ubuntu-latest
    environment: development
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Build Docker image
      run: |
        docker build -t ${{secrets.DOCKER_USERNAME}}/frontend:dev ./frontend
        docker tag ${{secrets.DOCKER_USERNAME}}/frontend:dev ${{secrets.DOCKER_USERNAME}}/frontend:${{github.sha}}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/frontend:dev
        docker push ${{secrets.DOCKER_USERNAME}}/frontend:${{github.sha}}
          
  dockerize-and-push-prod:
    needs: [test-frontend]
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/production'

    environment:
      name: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}

    - name: Build Docker image
      run: |
        docker build -t ${{secrets.DOCKER_USERNAME}}/frontend:prod ./frontend
        docker tag ${{secrets.DOCKER_USERNAME}}/frontend:prod ${{secrets.DOCKER_USERNAME}}/frontend:${{github.sha}}

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{secrets.DOCKER_USERNAME}}/frontend:prod
        docker push ${{secrets.DOCKER_USERNAME}}/frontend:${{github.sha}}

  deploy-to-firebase:
    needs: test-frontend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist/

    - name: Setup Firebase CLI
      run: |
        cd frontend
        npm install -g firebase-tools

    - name: Deploy to Firebase Hosting
      run: |
        cd frontend
        firebase deploy --only hosting --token ${{secrets.FIREBASE_TOKEN}}

  #GitHub Pages
  deploy-pages:
    needs: test-frontend
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./docs
